---
name: "fluentd"
home: "http://fabric8.io/fluentd/"
version: "2.2.120-SNAPSHOT"
description: "[Fluentd](http://www.fluentd.org/) is an open source data collector\
  \ for unified logging layer."
maintainers:
- "Fabric8 Development Team <fabric8@googlegroups.com>"
