---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    description: "Randomly kills pods to help check your environment can withstand\
      \ failures"
    fabric8.chaos-monkey/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/chaos-monkey/src/main/fabric8/icon.png"
    fabric8.chaos-monkey/summary: "Kills random pods for chaos fun!"
  labels: {}
  name: "chaos-monkey"
objects:
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "release-v2.2.91"
      fabric8.io/git-commit: "ad7d853e502c650efeb7a582cc54ecdde489bc48"
      fabric8.io/git-url: "http://gogs.release.cd.fabric8.io/gogsadmin/oss-parent/commit/ad7d853e502c650efeb7a582cc54ecdde489bc48"
      fabric8.io/build-url: "http://jenkins.release.cd.fabric8.io/job/oss-parent/2"
      fabric8.io/build-id: "2"
    labels:
      project: "chaosMonkey"
      provider: "fabric8"
      version: "2.2.91"
      group: "io.fabric8.devops.apps"
    name: "chaos-monkey"
  spec:
    replicas: 1
    selector:
      project: "chaosMonkey"
      provider: "fabric8"
      version: "2.2.91"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "chaosMonkey"
          provider: "fabric8"
          version: "2.2.91"
          group: "io.fabric8.devops.apps"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "CHAOS_MONKEY_INCLUDES"
            value: "${CHAOS_MONKEY_INCLUDES}"
          - name: "CHAOS_MONKEY_EXCLUDES"
            value: "${CHAOS_MONKEY_EXCLUDES}"
          - name: "CHAOS_MONKEY_ROOM"
            value: "${CHAOS_MONKEY_ROOM}"
          - name: "CHAOS_MONKEY_KILL_FREQUENCY_SECONDS"
            value: "${CHAOS_MONKEY_KILL_FREQUENCY_SECONDS}"
          - name: "KUBERNETES_MASTER"
            value: "https://kubernetes.default.svc"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/chaos-monkey:2.2.91"
          name: "chaos-monkey"
          ports:
          - containerPort: 8778
            name: "jolokia"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        serviceAccountName: "fabric8"
        volumes: []
parameters:
- description: "The chat room to talk to"
  name: "CHAOS_MONKEY_ROOM"
  value: "#fabric8_${namespace}"
- description: "Comma separated list of patterns for pods which should not be deleted"
  name: "CHAOS_MONKEY_EXCLUDES"
  value: "letschat*,gogs*"
- description: "Comma separated list of patterns for pods which should be considered\
    \ for deletion"
  name: "CHAOS_MONKEY_INCLUDES"
  value: "*"
- description: "The number of seconds between a kill"
  name: "CHAOS_MONKEY_KILL_FREQUENCY_SECONDS"
  value: "60"
