---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    description: "#Dispatch Router\nA high-performance, lightweight AMQP 1.0 message\
      \ router, written in C and built on Qpid Proton. It provides flexible and scalable\
      \ interconnect between any AMQP endpoints, whether they be clients, brokers\
      \ or other AMQP-enabled services. More about Dispatch Router.\n\n# Features\n\
      - Arbitrary topology - redundancy without restrictions\n- Automatic re-routing\
      \ when topology changes\n- Configurable addressing semantics\n- Run-time configuration\
      \ and query via management tools\n- Full support for the draft AMQP management\
      \ specification\n"
    fabric8.qpid-dispatch/summary: "A high-performance, lightweight AMQP 1.0 message\
      \ router"
    fabric8.qpid-dispatch/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8/master/fabric8-maven-plugin/src/main/resources/icons/activemq.svg"
  labels: {}
  name: "qpid-dispatch"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "qpid-dispatch"
      component: "qpid-dispatch"
      provider: "fabric8"
      version: "2.2.68"
      group: "qpid-dispatch"
    name: "qpid-dispatch"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 5672
      protocol: "TCP"
      targetPort: 5672
    selector:
      project: "qpid-dispatch"
      component: "qpid-dispatch"
      provider: "fabric8"
      group: "qpid-dispatch"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "6750a361fe0796777840dd5079bbeeff7ef3be2d"
      fabric8.io/git-commit: "6750a361fe0796777840dd5079bbeeff7ef3be2d"
      fabric8.io/git-url: "http://gogs.cd.fabric8.io/gogsadmin/oss-parent/commit/6750a361fe0796777840dd5079bbeeff7ef3be2d"
      fabric8.io/build-url: "http://jenkins.cd.fabric8.io/job/oss-parent/12"
      fabric8.io/build-id: "12"
    labels:
      project: "qpid-dispatch"
      component: "qpid-dispatch"
      provider: "fabric8"
      version: "2.2.68"
      group: "qpid-dispatch"
    name: "qpid-dispatch"
  spec:
    replicas: 1
    selector:
      project: "qpid-dispatch"
      component: "qpid-dispatch"
      provider: "fabric8"
      version: "2.2.68"
      group: "qpid-dispatch"
    template:
      metadata:
        annotations: {}
        labels:
          project: "qpid-dispatch"
          component: "qpid-dispatch"
          provider: "fabric8"
          version: "2.2.68"
          group: "qpid-dispatch"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/qpid-dispatch:latest"
          name: "qpid-dispatch"
          ports:
          - containerPort: 8778
            name: "jolokia"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters: []
