---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    fabric8.msg-gateway/iconUrl: "img/icons/activemq.svg"
    fabric8.msg-gateway/summary: "Control/Secure/Scale Enterprise Messaging"
    description: "An Enterprise Messaging Gateway that can apply policeis for scaling/security/rate\
      \ limiting etc."
  labels: {}
  name: "msg-gateway"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "msg-gateway"
      component: "msg-gateway"
      provider: "fabric8"
      version: "2.2.95"
      group: "msg-gateway"
    name: "msg-gateway"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 6163
      protocol: "TCP"
      targetPort: 6194
    selector:
      project: "msg-gateway"
      component: "msg-gateway"
      provider: "fabric8"
      group: "msg-gateway"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "release-v2.2.95"
      fabric8.io/git-commit: "9a124eeb7dafa0350f9b906fa8bceacb3c430763"
      fabric8.io/git-url: "http://gogs.release.cd.fabric8.io/gogsadmin/oss-parent/commit/9a124eeb7dafa0350f9b906fa8bceacb3c430763"
      fabric8.io/build-url: "http://jenkins.release.cd.fabric8.io/job/oss-parent/4"
      fabric8.io/build-id: "4"
    labels:
      project: "msg-gateway"
      component: "msg-gateway"
      provider: "fabric8"
      version: "2.2.95"
      group: "msg-gateway"
    name: "msg-gateway"
  spec:
    replicas: 1
    selector:
      project: "msg-gateway"
      component: "msg-gateway"
      provider: "fabric8"
      version: "2.2.95"
      group: "msg-gateway"
    template:
      metadata:
        annotations: {}
        labels:
          project: "msg-gateway"
          component: "msg-gateway"
          provider: "fabric8"
          version: "2.2.95"
          group: "msg-gateway"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/msg-gateway:2.2.95"
          name: "msg-gateway"
          ports:
          - containerPort: 6194
            name: "amq"
          - containerPort: 8778
            name: "jolokia"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters: []
