---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    fabric8.letschat/summary: "[Lets Chat](http://sdelements.github.io/lets-chat/)\
      \ Self-hosted chat for small teams"
    description: "[Let's Chat](https://github.com/sdelements/lets-chat) is an open\
      \ source chat server. It's designed to be easily deployable and fits well with\
      \ small, intimate teams"
    fabric8.letschat/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/letschat/src/main/fabric8/icon.png"
  labels: {}
  name: "letschat"
objects:
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "021bf3d7ca308e9087fa805e7639658766044658"
      fabric8.io/git-commit: "021bf3d7ca308e9087fa805e7639658766044658"
      fabric8.io/git-url: "http://gogs.cd.fabric8.io/gogsadmin/oss-parent/commit/021bf3d7ca308e9087fa805e7639658766044658"
      fabric8.io/build-url: "http://jenkins.cd.fabric8.io/job/oss-parent/15"
      fabric8.io/build-id: "15"
    labels:
      project: "letschat"
      provider: "fabric8"
      version: "2.2.76"
      group: "io.fabric8.devops.apps"
    name: "letschat"
  spec:
    replicas: 1
    selector:
      project: "letschat"
      provider: "fabric8"
      version: "2.2.76"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "letschat"
          provider: "fabric8"
          version: "2.2.76"
          group: "io.fabric8.devops.apps"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/letschat:2.2.76"
          name: "letschat"
          ports:
          - containerPort: 8778
            name: "jolokia"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters: []
