---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    description: "JFrog provides open source communities with solutions to automate\
      \ software package management.\nArtifactory, JFrog???s open source project,\
      \ was released to speed up development cycles using binary repositories.\nBintray,\
      \ JFrog???s social SaaS platform, was created for developers to distribute and\
      \ share their software.\nWith Artifactory and Bintray, JFrog is the only company\
      \ providing a complete platform for automated software package management from\
      \ development to distribution."
    fabric8.artifactory/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/artifactory/src/main/fabric8/icon.png"
    fabric8.artifactory/summary: "[Artifactory](http://www.jfrog.com/open-source/)\
      \ Open Source Maven Repository Manager"
  labels: {}
  name: "artifactory"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "artifactory"
      provider: "fabric8"
      version: "2.2.131"
      group: "io.fabric8.devops.apps"
    name: "artifactory"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 8081
    selector:
      project: "artifactory"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "release-v2.2.131"
      fabric8.io/git-commit: "6c76c22a0c1686122e0850f72385c67aab636db1"
      fabric8.io/git-url: "http://gogs.release.cd.fabric8.io/gogsadmin/oss-parent/commit/6c76c22a0c1686122e0850f72385c67aab636db1"
      fabric8.io/build-url: "http://jenkins.release.cd.fabric8.io/job/oss-parent/3"
      fabric8.io/build-id: "3"
    labels:
      project: "artifactory"
      provider: "fabric8"
      version: "2.2.131"
      group: "io.fabric8.devops.apps"
    name: "artifactory"
  spec:
    replicas: 1
    selector:
      project: "artifactory"
      provider: "fabric8"
      version: "2.2.131"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "artifactory"
          provider: "fabric8"
          version: "2.2.131"
          group: "io.fabric8.devops.apps"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "jfrog-docker-registry.bintray.io/artifactory/artifactory-oss"
          name: "artifactory"
          ports:
          - containerPort: 8081
            name: "http"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters: []
