---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    description: "Nexus is a maven repository manager\n \nMore details on the <a href=\"\
      http://www.sonatype.org/nexus/\" target=\"nexus\">Nexus home page</a>.\n"
    fabric8.nexus/summary: "[Nexus](http://www.sonatype.org/nexus/) - A maven repository\
      \ manager"
    fabric8.nexus/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/nexus/src/main/fabric8/icon.png"
  labels: {}
  name: "nexus"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "nexus"
      provider: "fabric8"
      version: "2.2.104"
      group: "io.fabric8.devops.apps"
    name: "nexus"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 8081
    selector:
      project: "nexus"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "release-v2.2.104"
      fabric8.io/git-commit: "df8e36b08230aa1698bb6c61012911c9662fc23d"
      fabric8.io/build-id: "6"
    labels:
      project: "nexus"
      provider: "fabric8"
      version: "2.2.104"
      group: "io.fabric8.devops.apps"
    name: "nexus"
  spec:
    replicas: 1
    selector:
      project: "nexus"
      provider: "fabric8"
      version: "2.2.104"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "nexus"
          provider: "fabric8"
          version: "2.2.104"
          group: "io.fabric8.devops.apps"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/nexus:2.2.104"
          imagePullPolicy: "IfNotPresent"
          name: "nexus"
          ports:
          - containerPort: 8081
            name: "http"
          securityContext: {}
          volumeMounts:
          - mountPath: "/sonatype-work/storage"
            name: "nexus-storage"
            readOnly: false
        imagePullSecrets: []
        nodeSelector: {}
        volumes:
        - emptyDir:
            medium: ""
          name: "nexus-storage"
parameters: []
