---
name: "elasticsearch-v1"
home: "http://fabric8.io/elasticsearch-v1/"
version: "2.2.93-SNAPSHOT"
description: "[elasticsearch](http://elasticsearch.com/) provides distributed RESTful\
  \ search and analytics"
maintainers:
- "Fabric8 Development Team"
