---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    fabric8.orion/summary: "[Orion](http://eclipse.org/orion/) is a web based IDE\
      \ for working files in a git repository"
    description: "The <a href=\"http://eclipse.org/orion/\" target=\"orion\">Orion</a>\
      \ is a web based IDE for working files in a git repository"
    fabric8.orion/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/orion/src/main/fabric8/icon.png"
  labels: {}
  name: "orion"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "orion"
      provider: "fabric8"
      version: "2.2.76"
      group: "io.fabric8.devops.apps"
    name: "orion"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "orion"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "021bf3d7ca308e9087fa805e7639658766044658"
      fabric8.io/git-commit: "021bf3d7ca308e9087fa805e7639658766044658"
      fabric8.io/git-url: "http://gogs.cd.fabric8.io/gogsadmin/oss-parent/commit/021bf3d7ca308e9087fa805e7639658766044658"
      fabric8.io/build-url: "http://jenkins.cd.fabric8.io/job/oss-parent/11"
      fabric8.io/build-id: "11"
    labels:
      project: "orion"
      provider: "fabric8"
      version: "2.2.76"
      group: "io.fabric8.devops.apps"
    name: "orion"
  spec:
    replicas: 1
    selector:
      project: "orion"
      provider: "fabric8"
      version: "2.2.76"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "orion"
          provider: "fabric8"
          version: "2.2.76"
          group: "io.fabric8.devops.apps"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/eclipse-orion:2.2.76"
          imagePullPolicy: "IfNotPresent"
          name: "orion"
          ports:
          - containerPort: 8080
            name: "http"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters: []
