---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    fabric8.orion/summary: "[Orion](http://eclipse.org/orion/) is a web based IDE\
      \ for working files in a git repository"
    description: "Provides an Open Source issue tracker via [Taiga](https://taiga.io/)\
      \ NOTE: default username/password admin/123123 and a web based IDE via <a href=\"\
      http://eclipse.org/orion/\" target=\"orion\">Orion</a>\n"
    fabric8.orion/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/orion/src/main/fabric8/icon.png"
    fabric8.social/summary: "Sonatype helps open source projects to set up Maven repositories\
      \ on https://oss.sonatype.org/"
    fabric8.social/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/packages/social/src/main/fabric8/icon.png"
  labels: {}
  name: "social"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "orion"
      provider: "fabric8"
      version: "2.2.113"
      group: "io.fabric8.devops.apps"
      package: "social"
    name: "orion"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "orion"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      provider: "fabric8"
      project: "taiga"
      package: "social"
    name: "taiga"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      targetPort: 80
    selector:
      provider: "fabric8"
      project: "taiga"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      provider: "fabric8"
      project: "taiga"
      package: "social"
    name: "taigaback"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 8000
      targetPort: 8000
    selector:
      provider: "fabric8"
      project: "taiga"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "release-v2.2.113"
      fabric8.io/git-commit: "98941ab606db9843c8011998d703f3e8189e3851"
      fabric8.io/git-url: "http://gogs.release.cd.fabric8.io/gogsadmin/oss-parent/commit/98941ab606db9843c8011998d703f3e8189e3851"
      fabric8.io/build-url: "http://jenkins.release.cd.fabric8.io/job/oss-parent/3"
      fabric8.io/build-id: "3"
    labels:
      project: "orion"
      provider: "fabric8"
      version: "2.2.113"
      group: "io.fabric8.devops.apps"
      package: "social"
    name: "orion"
  spec:
    replicas: 1
    selector:
      project: "orion"
      provider: "fabric8"
      version: "2.2.113"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "orion"
          provider: "fabric8"
          version: "2.2.113"
          group: "io.fabric8.devops.apps"
          package: "social"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/eclipse-orion:2.2.113"
          imagePullPolicy: "IfNotPresent"
          name: "orion"
          ports:
          - containerPort: 8080
            name: "http"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "release-v2.2.113"
      fabric8.io/git-commit: "98941ab606db9843c8011998d703f3e8189e3851"
      fabric8.io/git-url: "http://gogs.release.cd.fabric8.io/gogsadmin/oss-parent/commit/98941ab606db9843c8011998d703f3e8189e3851"
      fabric8.io/build-url: "http://jenkins.release.cd.fabric8.io/job/oss-parent/3"
      fabric8.io/build-id: "3"
    labels:
      provider: "fabric8"
      project: "taiga"
      package: "social"
    name: "taiga"
  spec:
    replicas: 1
    selector:
      provider: "fabric8"
      project: "taiga"
    template:
      metadata:
        annotations: {}
        labels:
          provider: "fabric8"
          project: "taiga"
          package: "social"
        name: "taiga"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "POSTGRES_PASSWORD"
            value: "password"
          - name: "POSTGRES_USER"
            value: "taiga"
          image: "postgres"
          name: "taiga-postgres"
          ports: []
          volumeMounts:
          - mountPath: "/var/lib/postgresql/data/"
            name: "taiga-data"
        - args: []
          command: []
          env:
          - name: "SECRET_KEY"
            value: "xyz"
          - name: "POSTGRES_PORT_5432_TCP_ADDR"
            value: "127.0.0.1"
          - name: "POSTGRES_ENV_POSTGRES_USER"
            value: "taiga"
          - name: "POSTGRES_ENV_POSTGRES_PASSWORD"
            value: "password"
          image: "fabric8/taiga-back:2.2.113"
          name: "taiga-backend"
          ports:
          - containerPort: 8000
            protocol: "TCP"
          volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: "taiga-data"
          - mountPath: "/usr/local/taiga/static"
            name: "taiga-static"
          - mountPath: "/usr/local/taiga/media"
            name: "taiga-media"
        - args: []
          command: []
          env: []
          image: "fabric8/taiga-front:2.2.113"
          name: "taiga-frontend"
          ports:
          - containerPort: 80
            protocol: "TCP"
          volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: "taiga-data"
          - mountPath: "/usr/local/taiga/static"
            name: "taiga-static"
          - mountPath: "/usr/local/taiga/media"
            name: "taiga-media"
        imagePullSecrets: []
        nodeSelector: {}
        volumes:
        - emptyDir: {}
          name: "taiga-data"
        - emptyDir: {}
          name: "taiga-static"
        - emptyDir: {}
          name: "taiga-media"
parameters: []
