---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    description: "##Apiman Gateway\n\nThe Apiman Gateway is part of API Management.\
      \ The Apiman Gateway requires the \nElasticsearch service to be up and running.\
      \ The Fabric8 gateway uses the Apiman engine to enforce policies and plans that\
      \ are published to the gateway using the Apiman management console. Note that\
      \ the Apiman management app runs in a different container.\n\nFor more details\
      \ please see the <a href=\"http://fabric8.io/guide/apimanComponents.html\">User\
      \ Guide on API Management </a> and the <a href=\"http://www.apiman.io/\">Apiman\
      \ website</a>.\n\nBy default this gateway is setup in the apiman management\
      \ console during the bootstrap process. You can check in this console under\
      \ admin > gateways > ApimanGateway using the 'Test Config' that connectivity\
      \ to the gateway is configured correctly (see also http://fabric8.io/guide/apimanGettingStarted.html).\n"
    fabric8.apiman-gateway/summary: "Apiman Gateway deployed on Jetty"
    fabric8.apiman-gateway/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/apiman-gateway/src/main/fabric8/icon.png"
  labels: {}
  name: "apiman-gateway"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      apiman.io/servicetype: "REST"
      apiman.io/descriptionpath: "api/swagger.json"
      apiman.io/descriptiontype: "SwaggerJSON"
      apiman.io/servicepath: "api"
    labels:
      project: "apiman-gateway"
      component: "ApimanGateway"
      provider: "fabric8"
      version: "2.2.87"
      group: "defaultGatewayGroup"
    name: "apiman-gateway"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 7777
      protocol: "TCP"
      targetPort: 7777
    selector:
      project: "apiman-gateway"
      component: "ApimanGateway"
      provider: "fabric8"
      group: "defaultGatewayGroup"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "release-v2.2.87"
      fabric8.io/git-commit: "f17b0ce893c6a18e461ec1a5297083de27399056"
      fabric8.io/git-url: "http://gogs.release.cd.fabric8.io/gogsadmin/oss-parent/commit/f17b0ce893c6a18e461ec1a5297083de27399056"
      fabric8.io/build-url: "http://jenkins.release.cd.fabric8.io/job/oss-parent/10"
      fabric8.io/build-id: "10"
    labels:
      project: "apiman-gateway"
      component: "ApimanGateway"
      provider: "fabric8"
      version: "2.2.87"
      group: "defaultGatewayGroup"
    name: "apiman-gateway"
  spec:
    replicas: 1
    selector:
      project: "apiman-gateway"
      component: "ApimanGateway"
      provider: "fabric8"
      version: "2.2.87"
      group: "defaultGatewayGroup"
    template:
      metadata:
        annotations: {}
        labels:
          project: "apiman-gateway"
          component: "ApimanGateway"
          provider: "fabric8"
          version: "2.2.87"
          group: "defaultGatewayGroup"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "AB_JOLOKIA_AUTH_OPENSHIFT"
            value: "true"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/apiman-gateway:2.2.87"
          name: "apiman-gateway"
          ports:
          - containerPort: 7777
            name: "http"
          - containerPort: 8778
            name: "jolokia"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters: []
