---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    fabric8.hubot-notifier/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-notifier/src/main/fabric8/icon.png"
    description: "Watches the OpenShift environment and notifies Hubot of events such\
      \ as builds completing or failing."
    fabric8.hubot-notifier/summary: "Watches the OpenShift environment and notifies\
      \ Hubot of events such as builds completing or failing"
  labels: {}
  name: "hubot-notifier"
objects:
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "release-v2.2.126"
      fabric8.io/git-commit: "bf79177b222f81c8b42bd4db7de7d78f46691ff7"
      fabric8.io/git-url: "http://gogs.release.cd.fabric8.io/gogsadmin/oss-parent/commit/bf79177b222f81c8b42bd4db7de7d78f46691ff7"
      fabric8.io/build-url: "http://jenkins.release.cd.fabric8.io/job/oss-parent/11"
      fabric8.io/build-id: "11"
    labels:
      project: "hubotNotifier"
      provider: "fabric8"
      version: "2.2.126"
      group: "io.fabric8.devops.apps"
    name: "hubot-notifier"
  spec:
    replicas: 1
    selector:
      project: "hubotNotifier"
      provider: "fabric8"
      version: "2.2.126"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "hubotNotifier"
          provider: "fabric8"
          version: "2.2.126"
          group: "io.fabric8.devops.apps"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "HUBOT_KUBERNETES_ROOM"
            value: "#fabric8_${namespace}"
          - name: "HUBOT_USERNAME"
            value: "${HUBOT_USERNAME}"
          - name: "HUBOT_PASSWORD"
            value: "${HUBOT_PASSWORD}"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/hubot-notifier:2.2.126"
          name: "hubot-notifier"
          ports:
          - containerPort: 8778
            name: "jolokia"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        serviceAccountName: "fabric8"
        volumes: []
parameters:
- description: "The DNS domain added to the serviceName.namespace.svc. to make the\
    \ DNS name"
  name: "KUBERNETES_DNS_DOMAIN"
  value: "cluster.local"
- description: "The password for Hubot to login to the chat service"
  name: "HUBOT_PASSWORD"
  value: "RedHat$1"
- description: "The username for Hubot to login to the chat service"
  name: "HUBOT_USERNAME"
  value: "fabric8"
