---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    fabric8.fabric8mq/summary: "Fabric8 MQ Broker"
    description: "runs a Fabric8 MQ broker based on [Apache ActiveMQ](http://activemq.apache.org/)\
      \ which is then exposed as a [kubernetes service](http://fabric8.io/v2/services.html)\
      \ so that clients can easily connect."
    fabric8.fabric8mq/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/fabric8mq/src/main/fabric8/icon.svg"
  labels: {}
  name: "fabric8mq"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "fabric8mq"
      component: "fabric8MQ"
      provider: "fabric8"
      version: "2.2.84"
      group: "fabric8mq"
    name: "fabric8mq"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 6163
      protocol: "TCP"
      targetPort: 6194
    selector:
      project: "fabric8mq"
      component: "fabric8MQ"
      provider: "fabric8"
      group: "fabric8mq"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "release-v2.2.84"
      fabric8.io/git-commit: "f69f0b345daf2fcfa5e7b0ddde3440d618109c4e"
      fabric8.io/git-url: "http://gogs.release.cd.fabric8.io/gogsadmin/oss-parent/commit/f69f0b345daf2fcfa5e7b0ddde3440d618109c4e"
      fabric8.io/build-url: "http://jenkins.release.cd.fabric8.io/job/oss-parent/1"
      fabric8.io/build-id: "1"
    labels:
      project: "fabric8mq"
      component: "fabric8MQ"
      provider: "fabric8"
      version: "2.2.84"
      group: "fabric8mq"
    name: "fabric8mq"
  spec:
    replicas: 1
    selector:
      project: "fabric8mq"
      component: "fabric8MQ"
      provider: "fabric8"
      version: "2.2.84"
      group: "fabric8mq"
    template:
      metadata:
        annotations: {}
        labels:
          project: "fabric8mq"
          component: "fabric8MQ"
          provider: "fabric8"
          version: "2.2.84"
          group: "fabric8mq"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_TRUST_CERT"
            value: "true"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/fabric8mq:2.2.84"
          name: "fabric8mq"
          ports:
          - containerPort: 6194
            name: "amq"
          - containerPort: 8778
            name: "jolokia"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        serviceAccountName: "fabric8"
        volumes: []
parameters: []
