---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    fabric8.fabric8-msm/summary: "Artemis configured for Microservice Messaging"
    description: "runs a [Apache ActiveMQ Artemis](https://activemq.apache.org/artemis/)\
      \ broker which is then exposed as a [kubernetes service](http://fabric8.io/v2/services.html).\n"
    fabric8.fabric8-msm/iconUrl: "img/icons/activemq.svg"
  labels: {}
  name: "fabric8-msm"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "fabric8-msm"
      component: "msm"
      provider: "fabric8"
      version: "2.2.94"
      group: "msm"
    name: "fabric8-msm"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 6163
      protocol: "TCP"
      targetPort: 6194
    selector:
      project: "fabric8-msm"
      component: "msm"
      provider: "fabric8"
      group: "msm"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "release-v2.2.94"
      fabric8.io/git-commit: "e77c669fc153bab2830d821b844d5a3a1ac0a7c5"
      fabric8.io/git-url: "http://gogs.release.cd.fabric8.io/gogsadmin/oss-parent/commit/e77c669fc153bab2830d821b844d5a3a1ac0a7c5"
      fabric8.io/build-url: "http://jenkins.release.cd.fabric8.io/job/oss-parent/3"
      fabric8.io/build-id: "3"
    labels:
      project: "fabric8-msm"
      component: "msm"
      provider: "fabric8"
      version: "2.2.94"
      group: "msm"
    name: "fabric8-msm"
  spec:
    replicas: 1
    selector:
      project: "fabric8-msm"
      component: "msm"
      provider: "fabric8"
      version: "2.2.94"
      group: "msm"
    template:
      metadata:
        annotations: {}
        labels:
          project: "fabric8-msm"
          component: "msm"
          provider: "fabric8"
          version: "2.2.94"
          group: "msm"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/fabric8-msm:2.2.94"
          name: "fabric8-msm"
          ports:
          - containerPort: 6194
            name: "amq"
          - containerPort: 8778
            name: "jolokia"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters: []
