---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    description: "runs a [Apache ActiveMQ](http://activemq.apache.org/) broker which\
      \ is then exposed as a [kubernetes service](http://fabric8.io/v2/services.html).\n"
    fabric8.amqbroker/iconUrl: "img/icons/activemq.svg"
    fabric8.amqbroker/summary: "ActiveMQ Broker"
  labels: {}
  name: "amqbroker"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "amqbroker"
      component: "amqbroker"
      provider: "fabric8"
      version: "2.2.95"
      group: "amqbroker"
    name: "amqbroker"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 6163
      protocol: "TCP"
      targetPort: 6194
    selector:
      project: "amqbroker"
      component: "amqbroker"
      provider: "fabric8"
      group: "amqbroker"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "release-v2.2.95"
      fabric8.io/git-commit: "9a124eeb7dafa0350f9b906fa8bceacb3c430763"
      fabric8.io/git-url: "http://gogs.release.cd.fabric8.io/gogsadmin/oss-parent/commit/9a124eeb7dafa0350f9b906fa8bceacb3c430763"
      fabric8.io/build-url: "http://jenkins.release.cd.fabric8.io/job/oss-parent/4"
      fabric8.io/build-id: "4"
    labels:
      project: "amqbroker"
      component: "amqbroker"
      provider: "fabric8"
      version: "2.2.95"
      group: "amqbroker"
    name: "amqbroker"
  spec:
    replicas: 1
    selector:
      project: "amqbroker"
      component: "amqbroker"
      provider: "fabric8"
      version: "2.2.95"
      group: "amqbroker"
    template:
      metadata:
        annotations: {}
        labels:
          project: "amqbroker"
          component: "amqbroker"
          provider: "fabric8"
          version: "2.2.95"
          group: "amqbroker"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "AB_JOLOKIA_AUTH_OPENSHIFT"
            value: "true"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/amqbroker:2.2.95"
          name: "amqbroker"
          ports:
          - containerPort: 6194
            name: "amq"
          - containerPort: 8778
            name: "jolokia"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters: []
