---
apiVersion: "v1"
items:
- apiVersion: "v1"
  imagePullSecrets: []
  kind: "ServiceAccount"
  metadata:
    annotations: {}
    labels:
      package: "console-kubernetes"
    name: "fabric8"
  secrets: []
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "console"
      provider: "fabric8"
      version: "2.2.81"
      group: "io.fabric8.devops.apps"
      package: "console-kubernetes"
    name: "fabric8"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 9090
    selector:
      project: "console"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "templates"
      provider: "fabric8"
      version: "2.2.81"
      group: "io.fabric8.devops.apps"
      package: "console-kubernetes"
    name: "templates"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "templates"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-commit: "c568041ef5980c9642814a7c40fec3787296e24f"
      fabric8.io/git-branch: "release-v2.2.81"
      fabric8.io/git-url: "http://gogs.cd.fabric8.io/gogsadmin/oss-parent/commit/c568041ef5980c9642814a7c40fec3787296e24f"
      fabric8.io/build-id: "1"
      fabric8.io/build-url: "http://jenkins.cd.fabric8.io/job/oss-parent/1"
    labels:
      project: "console"
      provider: "fabric8"
      version: "2.2.81"
      group: "io.fabric8.devops.apps"
      package: "console-kubernetes"
    name: "fabric8"
  spec:
    replicas: 1
    selector:
      project: "console"
      provider: "fabric8"
      version: "2.2.81"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "console"
          provider: "fabric8"
          version: "2.2.81"
          group: "io.fabric8.devops.apps"
          package: "console-kubernetes"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "GOOGLE_OAUTH_SCOPE"
            value: "profile"
          - name: "OAUTH_AUTHORIZE_PORT"
            value: "8443"
          - name: "GOOGLE_OAUTH_CLIENT_ID"
            value: ""
          - name: "OAUTH_AUTHORIZE_URI"
            value: "https://vagrant.f8:8443/oauth/authorize"
          - name: "GOOGLE_OAUTH_AUTHENTICATION_URI"
            value: "https://accounts.google.com/o/oauth2/auth"
          - name: "GOOGLE_OAUTH_CLIENT_SECRET"
            value: ""
          - name: "OAUTH_CLIENT_ID"
            value: "fabric8"
          - name: "OAUTH_PROVIDER"
            value: "basic"
          - name: "GOOGLE_OAUTH_REDIRECT_URI"
            value: "https://fabric8.vagrant.f8"
          - name: "GOOGLE_OAUTH_TOKEN_URL"
            value: "https://www.googleapis.com/oauth2/v3/token"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/fabric8-console:2.2.81"
          name: "fabric8-container"
          ports:
          - containerPort: 9090
            name: "http"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "release-v2.2.81"
      fabric8.io/git-commit: "c568041ef5980c9642814a7c40fec3787296e24f"
      fabric8.io/git-url: "http://gogs.cd.fabric8.io/gogsadmin/oss-parent/commit/c568041ef5980c9642814a7c40fec3787296e24f"
      fabric8.io/build-url: "http://jenkins.cd.fabric8.io/job/oss-parent/1"
      fabric8.io/build-id: "1"
    labels:
      project: "templates"
      provider: "fabric8"
      version: "2.2.81"
      group: "io.fabric8.devops.apps"
      package: "console-kubernetes"
    name: "templates"
  spec:
    replicas: 1
    selector:
      project: "templates"
      provider: "fabric8"
      version: "2.2.81"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "templates"
          provider: "fabric8"
          version: "2.2.81"
          group: "io.fabric8.devops.apps"
          package: "console-kubernetes"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "DATA_DIR"
            value: "/data/templates"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/templates:2.2.81"
          name: "templates"
          ports:
          - containerPort: 8080
            name: "http"
          - containerPort: 8778
            name: "jolokia"
          securityContext: {}
          volumeMounts:
          - mountPath: "/data"
            name: "template-data"
            readOnly: false
        imagePullSecrets: []
        nodeSelector: {}
        volumes:
        - gitRepo:
            repository: "https://github.com/fabric8io/templates.git"
            revision: "master"
          name: "template-data"
kind: "List"
