---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    description: "Provides chat friendly links"
    fabric8.image-linker/summary: "Provides embedded chat friendly links to images"
    fabric8.image-linker/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/image-linker/src/main/fabric8/icon.svg"
  labels: {}
  name: "image-linker"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "imageLinker"
      provider: "fabric8"
      version: "2.2.107"
      group: "io.fabric8.devops.apps"
    name: "image-linker"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 8080
    selector:
      project: "imageLinker"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "release-v2.2.107"
      fabric8.io/git-commit: "dd1069e6a8ee5f2f350e56cbff265ccd7e488870"
      fabric8.io/git-url: "http://gogs.release.cd.fabric8.io/gogsadmin/oss-parent/commit/dd1069e6a8ee5f2f350e56cbff265ccd7e488870"
      fabric8.io/build-url: "http://jenkins.release.cd.fabric8.io/job/oss-parent/2"
      fabric8.io/build-id: "2"
    labels:
      project: "imageLinker"
      provider: "fabric8"
      version: "2.2.107"
      group: "io.fabric8.devops.apps"
    name: "image-linker"
  spec:
    replicas: 1
    selector:
      project: "imageLinker"
      provider: "fabric8"
      version: "2.2.107"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "imageLinker"
          provider: "fabric8"
          version: "2.2.107"
          group: "io.fabric8.devops.apps"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/image-linker:2.2.107"
          name: "image-linker"
          ports:
          - containerPort: 8080
            name: "http"
          - containerPort: 8778
            name: "jolokia"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters: []
