---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    description: "[Kibana](http://www.elasticsearch.org/overview/kibana/) lets you\
      \ view, filter and search all logs and events that have been written to Elasticsearch.\n"
    fabric8.kibana/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/kibana/src/main/fabric8/icon.svg"
    fabric8.kibana/summary: "Awesome front-end for Elasticsearch"
  labels: {}
  name: "kibana"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "kibana"
      provider: "fabric8"
      version: "2.2.80-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    name: "kibana"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 5601
    selector:
      project: "kibana"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-commit: "f2329fc83866c6bc71cb4774e52c3b6d75da3fec"
      fabric8.io/git-branch: "release-v2.2.79"
      fabric8.io/git-url: "http://gogs.cd.fabric8.io/gogsadmin/oss-parent/commit/f2329fc83866c6bc71cb4774e52c3b6d75da3fec"
      fabric8.io/build-id: "6"
      fabric8.io/build-url: "http://jenkins.cd.fabric8.io/job/oss-parent/6"
    labels:
      project: "kibana"
      provider: "fabric8"
      version: "2.2.80-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    name: "kibana"
  spec:
    replicas: 1
    selector:
      project: "kibana"
      provider: "fabric8"
      version: "2.2.80-SNAPSHOT"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "kibana"
          provider: "fabric8"
          version: "2.2.80-SNAPSHOT"
          group: "io.fabric8.devops.apps"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "ELASTICSEARCH_URL"
            value: "http://elasticsearch:9200"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/kibana4:4.3.0"
          livenessProbe:
            tcpSocket:
              port: 5601
          name: "kibana"
          ports:
          - containerPort: 5601
            name: "http"
          securityContext: {}
          volumeMounts: []
        - args: []
          command: []
          env:
          - name: "ELASTICSEARCH_URL"
            value: "http://elasticsearch:9200"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/kibana-config:2.2.80-SNAPSHOT"
          name: "kibana-config"
          ports: []
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters: []
