---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    description: "Grafana is an open source, feature rich metrics dashboard and graph\
      \ editor for Graphite, InfluxDB & OpenTSDB.\n\nMore details on the <a href=\"\
      http://grafana.org/\" target=\"wikipedia\">Grafana home page</a>.\n"
    fabric8.grafana2/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/grafana2/src/main/fabric8/icon.png"
    fabric8.grafana2/summary: "[Grafana](http://grafana.org/) 2 console for viewing\
      \ metrics stored in various storage backends"
  labels: {}
  name: "grafana2"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "grafana2"
      provider: "fabric8"
      version: "2.2.133"
      group: "io.fabric8.devops.apps"
    name: "grafana2"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 80
      protocol: "TCP"
      targetPort: 3000
    selector:
      project: "grafana2"
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    type: "LoadBalancer"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "release-v2.2.133"
      fabric8.io/git-commit: "eea056bd59ca5f4d5f4ec7bc88c65bc9ec21c55f"
      fabric8.io/git-url: "http://gogs.release.cd.fabric8.io/gogsadmin/oss-parent/commit/eea056bd59ca5f4d5f4ec7bc88c65bc9ec21c55f"
      fabric8.io/build-url: "http://jenkins.release.cd.fabric8.io/job/oss-parent/2"
      fabric8.io/build-id: "2"
    labels:
      project: "grafana2"
      provider: "fabric8"
      version: "2.2.133"
      group: "io.fabric8.devops.apps"
    name: "grafana2"
  spec:
    replicas: 1
    selector:
      project: "grafana2"
      provider: "fabric8"
      version: "2.2.133"
      group: "io.fabric8.devops.apps"
    template:
      metadata:
        annotations: {}
        labels:
          project: "grafana2"
          provider: "fabric8"
          version: "2.2.133"
          group: "io.fabric8.devops.apps"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "PROMETHEUS_ADDRESS"
            value: "http://prometheus"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/grafana:2.5.0_01"
          name: "grafana2"
          ports:
          - containerPort: 3000
            name: "http"
          securityContext: {}
          volumeMounts:
          - mountPath: "/var/lib/grafana"
            name: "grafana-data"
            readOnly: false
        imagePullSecrets: []
        nodeSelector: {}
        volumes:
        - emptyDir:
            medium: ""
          name: "grafana-data"
parameters: []
