---
apiVersion: "v1"
kind: "Template"
labels: {}
metadata:
  annotations:
    fabric8.artemis/summary: "Enterprise Message Broker"
    description: "Apache ActiveMQ Artemis is a enterprise Message broker -supporting\
      \ JMS 2.0 and AMQP/OpenWire/MQTT/STOMP wire protocols\n"
    fabric8.artemis/iconUrl: "img/icons/activemq.svg"
  labels: {}
  name: "artemis"
objects:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations: {}
    labels:
      project: "artemis"
      component: "artemis"
      provider: "fabric8"
      version: "2.2.94"
      group: "artemis"
    name: "artemis"
  spec:
    deprecatedPublicIPs: []
    externalIPs: []
    ports:
    - port: 6163
      protocol: "TCP"
      targetPort: 6194
    selector:
      project: "artemis"
      component: "artemis"
      provider: "fabric8"
      group: "artemis"
- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    annotations:
      fabric8.io/git-branch: "release-v2.2.94"
      fabric8.io/git-commit: "e77c669fc153bab2830d821b844d5a3a1ac0a7c5"
      fabric8.io/git-url: "http://gogs.release.cd.fabric8.io/gogsadmin/oss-parent/commit/e77c669fc153bab2830d821b844d5a3a1ac0a7c5"
      fabric8.io/build-url: "http://jenkins.release.cd.fabric8.io/job/oss-parent/3"
      fabric8.io/build-id: "3"
    labels:
      project: "artemis"
      component: "artemis"
      provider: "fabric8"
      version: "2.2.94"
      group: "artemis"
    name: "artemis"
  spec:
    replicas: 1
    selector:
      project: "artemis"
      component: "artemis"
      provider: "fabric8"
      version: "2.2.94"
      group: "artemis"
    template:
      metadata:
        annotations: {}
        labels:
          project: "artemis"
          component: "artemis"
          provider: "fabric8"
          version: "2.2.94"
          group: "artemis"
      spec:
        containers:
        - args: []
          command: []
          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "fabric8/artemis:2.2.94"
          name: "artemis"
          ports:
          - containerPort: 6194
            name: "amq"
          - containerPort: 8778
            name: "jolokia"
          securityContext: {}
          volumeMounts: []
        imagePullSecrets: []
        nodeSelector: {}
        volumes: []
parameters: []
